### ISSUE TITLE
Missing assets when using jQuery datepicker

### ISSUE THREAD

**Issue by UVLabs** [iconicwp/WordPress-Settings-Framework#106]
I'm not making use of it but I noticed the errors when checking out the examples:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/10324144/227843275-a86cd8d9-f638-47ca-bfee-f6360d5c3af5.png">

Those files are attempting to be loaded by the datepicker CSS.

**Comment by Rahmon** [comment]
Closing in favour of #113
