### ISSUE TITLE
Weird errors when trying to instantiate class inside a plugin

### ISSUE THREAD

**Issue by danilomedeirosmusica** [iconicwp/WordPress-Settings-Framework#84]
I'm getting two errors when trying to instantiate the wpsf class from inside a plugin:

Notice: Undefined index: slug in /var/www/html/wp-content/plugins/apoiase/classes/wp-settings-framework/wp-settings-framework.php on line 201

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/apoiase/classes/wp-settings-framework/wp-settings-framework.php:201

Any ideas? Note that I'm instantiating it inside a "classes" folder.

**Comment by namespace-dave** [comment]
hi @danilomedeirosmusica are you able to provide access to the code you're using, or share it here? If you are passing an option group slug in as the second parameter which initialising `WordPressSettingsFramework`, the `construct_settings()` method in the framework should be setting the settings page slug value automatically.

The second warning relating to header information suggests that content has already been sent to the browser, meaning that no additional headers can be sent. I would check your plugin codebase to see if anything is generating output before the settings framework class is initialised.

**Comment by namespace-dave** [comment]
hi @danilomedeirosmusica just checking in to see if this is still an issue? If not, we can close this off. Thanks!

**Comment by danilomedeirosmusica** [comment]
Please do. I ended up doing the code manually, will come back to this as
soon as possible.

Em seg., 12 de set. de 2022 14:45, Dave Green ***@***.***>
escreveu:
